# Generated by Django 2.1.5 on 2020-12-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aiscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('partner', models.CharField(max_length=100)),
                ('describe', models.CharField(max_length=2000)),
                ('createdate', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '项目信息表',
                'ordering': ['-createdate'],
            },
        ),
    ]
