# Generated by Django 2.1.5 on 2020-12-02 08:44

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aidata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='项目名称')),
                ('createdate', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('content_text', DjangoUeditor.models.UEditorField(default='', verbose_name='数据和评价指标')),
            ],
            options={
                'verbose_name_plural': '数据和评价指标',
            },
        ),
        migrations.CreateModel(
            name='Aidemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='项目名称')),
                ('createdate', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='效果展示')),
            ],
            options={
                'verbose_name_plural': '效果展示',
                'get_latest_by': 'createdate',
            },
        ),
        migrations.CreateModel(
            name='Aidetial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='项目名称')),
                ('createdate', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='项目介绍')),
            ],
            options={
                'verbose_name_plural': '项目细节',
                'get_latest_by': 'createdate',
            },
        ),
        migrations.CreateModel(
            name='Aisort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='项目名称')),
                ('model_name', models.CharField(max_length=200, verbose_name='使用的模型')),
                ('score', models.FloatField(verbose_name='得分')),
                ('test_type', models.CharField(max_length=20, verbose_name='榜单类型')),
                ('createdate', models.DateField(auto_now_add=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '项目排名',
            },
        ),
    ]
